name: Increment @version

on:
  push:
    branches:
      - main # This workflow runs on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # The job will run on a fresh Ubuntu virtual machine

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # This action checks out your repository under $GITHUB_WORKSPACE

      - name: Update @version
        run: |
              current_date=$(date +"%Y-%m-%d")
              echo "Current date: $current_date"
              file_version=$(grep "^\/\/ @version +(\d{4})-(\d{2})-(\d{2}).(\d+)$" "hsreplay-bgs-comps.js" | awk -F': ' '{print $2}')
              echo "File version: $file_version"
              IFS="." read -ra parts <<< "file_version"
              file_date=${parts[0]}
              file_version_number=${parts[1]}
              echo "File date: $file_date"
              echo "File version number: $file_version_number"
              if [[ $current_date != $file_date ]]; then
                echo "Current and file dates are different"
                file_version_number=1
              else
                echo "Current and file dates are the same"
                ((file_version_number++))
              fi
              sed -i 's/^\/\/ @version( +)(\d{4})-(\d{2})-(\d{2}).(\d+)$/\/\/ @version$1${current_date}.${file_version_number}/g' hsreplay-bgs-comps.js
